### ISSUE TITLE
gee this code looks familiar....

### ISSUE THREAD

**Issue by timbophillips** [itsmebhavin/angular-cli-pouchdb-couchdb#2]
hmm i can't see a reference to any original authors?

**Comment by bapatel1** [comment]
@timbophillips I am not claiming that I am original author as well. This is something i learned from referring various articles and created sample app for my own knowledge purpose. Instead of learning and looking into code content, if you are in interested in finding who is the real author and all, certainly i can find original article and put a link and name here. 

Thanks,

**Comment by timbophillips** [comment]
hi thanks for getting back to me. it is almost entirely code that i wrote so it would be interesting to know which article it featured in - please do let me know.

i've since updated a lot of it making it more robust and streamlined. also went with material rather than bootstrap in the end

**Comment by itsmebhavin** [comment]
@timbophillips thank you so much for great code like i mentioned. I have no problem putting your name (infact, i just did, you can check readme). I just did it to learn and yes, your code helped me out a lot and still using the concept in prod based projects. 

Regarding changes you have done, certainly i will check. 
Thanks,

**Comment by itsmebhavin** [comment]
@timbophillips You may also check my G+ collection `https://plus.google.com/collection/EWXpb` and you will see that i am just having one place repository to all good articles and all material to just help others. knowledge sharing !! Not claiming that i am the author of those article though. 😄
